#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
BASE_DIR=/home/cui/log_analytics
BIN_DIR=$BASE_DIR/bin
COMMAND=$BIN_DIR/analytics
LOG_FILE=$BASE_DIR/log/online.log
CONFIG_FILE=$BASE_DIR/configs/config.py
PID_FILE=$BASE_DIR/analytics.pid
SSH_USER=mhgame

_start() {
    echo 'start: ', $COMMAND
    sudo -u $SSH_USER $COMMAND -l $LOG_FILE -c $CONFIG_FILE -p $PID_FILE -s 'start'
}

_stop() {
    echo 'Stop: ', $COMMAND
    $COMMAND -s 'stop'
    ps -ef | grep analytics | grep -v grep | awk '{print $2}' | xargs kill

}

_status() {
    ps -ef | grep analytics | grep -v grep | grep python
}

case "$1" in 
    start)
	_start
	;;
    stop)
	_stop
	;;
    status)
	_status
	;;
    restart|reload)
	_stop
	_start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
exit 0
